defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

wandb:
  entity: frauke
  project: MI-SegNet

files:
  image_path: S:\Slides\SegmentationMultiScanner
  annotation_file: S:\Slides\SegmentationMultiScanner\scc-full-res.json
  result_dir: .\MI_Netresult

data:
  patch_size: 256
  batch_size: null
  batch_base: 2 #8
  ds_factor: 4
  patches_per_slide: 8

model:
    embed_dim: 4
    n_embed: 1024
    sane_index_shape: False,  # tell vector quantizer to return indices as bhw
    input_channel: 3
    output_channel: 3
    init_feature: 32
    max_grad_norm: 10
    decoder_channels: 1280
    double_z: True
    z_channels: 4
    resolution: 256
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1,4,8]
    num_res_blocks: 2
    attn_resolutions: [ ]
    dropout: 0.0

cluster:
  n_gpus: 1
  batch_mul: 1
  n_workers: 0
  backend: gloo #nccl

training:
  seed: 42
  scanner_A: cs2
  scanner_B: nz20
  lr: 1e-4
  epochs: 200