wandb:
  entity: frauke
  project: MI-SegNet
  dir: /Users/fraukewilm/Code/MI-SegNet/

files:
  image_path: null
  annotation_file: /Volumes/SLIDES/Slides/SegmentationMultiScanner/scc-full-res.json

data:
  fold: null
  patch_size: 256
  batch_size: null
  batch_base: 2 #8
  ds_factor: 4
  patches_per_slide: 8
  hed: True

model:
  input_channel: 3
  output_channel: 3
  init_feature: 32
  max_grad_norm: 10

cluster:
  n_gpus: 1
  batch_mul: 1
  n_workers: 2
  backend: gloo #nccl

training:
  seed: 42
  scanner_A: cs2
  scanner_B: nz20
  lr: 0.0001
  epochs: 200

loss:
  w_l1: 1.0
  w_ssim: 1.0
  w_p: 1.0
  w_d: 0.0